{"type": "request", "data": {"timestamp": 1740462197.183789, "service": "AIService", "operation": "extract_wahrheit_data", "success": false, "duration": 2.1457672119140625e-06, "metadata": {"error_type": "unknown"}}, "system_uptime": 7.185104131698608}
{"type": "retry", "data": {"timestamp": 1740462197.184043, "service": "AIService", "operation": "extract_wahrheit_data", "attempt": 1, "error_message": "load_wahrheit.<locals>.extract() got an unexpected keyword argument 'metadata'", "metadata": {"error_type": "unknown"}}, "system_uptime": 7.185357093811035}
{"type": "request", "data": {"timestamp": 1740462199.186173, "service": "AIService", "operation": "extract_wahrheit_data", "success": false, "duration": 5.0067901611328125e-06, "metadata": {"error_type": "unknown"}}, "system_uptime": 9.187487840652466}
{"type": "retry", "data": {"timestamp": 1740462199.1863701, "service": "AIService", "operation": "extract_wahrheit_data", "attempt": 2, "error_message": "load_wahrheit.<locals>.extract() got an unexpected keyword argument 'metadata'", "metadata": {"error_type": "unknown"}}, "system_uptime": 9.187684059143066}
{"type": "error", "data": {"timestamp": 1740462199.186652, "service": "FileProcessor", "operation": "extract_wahrheit_data", "error_message": "Failed to process extract_wahrheit_data after 2 attempts. Last error: load_wahrheit.<locals>.extract() got an unexpected keyword argument 'metadata'", "metadata": {"total_duration": 2.0033321380615234}}, "system_uptime": 9.18796682357788}
{"type": "error", "data": {"timestamp": 1740462199.187108, "service": "PackingListGenerator", "operation": "generate_packing_list", "error_message": "Error processing wahrheit data: Failed to process extract_wahrheit_data after 2 attempts. Last error: load_wahrheit.<locals>.extract() got an unexpected keyword argument 'metadata'", "metadata": {"total_duration": 2.0039072036743164}}, "system_uptime": 9.188422203063965}
