{"type": "request", "data": {"timestamp": 1740498366.017005, "service": "AIService", "operation": "extract_wahrheit_data", "success": false, "duration": 1.0013580322265625e-05, "metadata": {"error_type": "unknown"}}, "system_uptime": 11.36347222328186}
{"type": "retry", "data": {"timestamp": 1740498366.017405, "service": "AIService", "operation": "extract_wahrheit_data", "attempt": 1, "error_message": "'\\n  \"invoice_no\"'", "metadata": {"error_type": "unknown"}}, "system_uptime": 11.363872051239014}
{"type": "request", "data": {"timestamp": 1740498368.0241432, "service": "AIService", "operation": "extract_wahrheit_data", "success": false, "duration": 2.288818359375e-05, "metadata": {"error_type": "unknown"}}, "system_uptime": 13.370613098144531}
{"type": "retry", "data": {"timestamp": 1740498368.024572, "service": "AIService", "operation": "extract_wahrheit_data", "attempt": 2, "error_message": "'\\n  \"invoice_no\"'", "metadata": {"error_type": "unknown"}}, "system_uptime": 13.371040105819702}
{"type": "error", "data": {"timestamp": 1740498368.024747, "service": "FileProcessor", "operation": "extract_wahrheit_data", "error_message": "Failed to process extract_wahrheit_data after 2 attempts. Last error: '\\n  \"invoice_no\"'", "metadata": {"total_duration": 2.0082859992980957}}, "system_uptime": 13.371214151382446}
{"type": "error", "data": {"timestamp": 1740498368.025548, "service": "PackingListGenerator", "operation": "generate_packing_list", "error_message": "Error processing wahrheit data: Failed to process extract_wahrheit_data after 2 attempts. Last error: '\\n  \"invoice_no\"'", "metadata": {"total_duration": 2.0092689990997314}}, "system_uptime": 13.372014284133911}
